version: '3.8'

services:
  app:
    build: .
    # The ports mapping is ignored when network_mode is host.
    # The application will be accessible on port 80 of the host.
    network_mode: "host"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=bourseauxjouets
      - DB_USER=user
      - DB_PASSWORD=password

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: bourseauxjouets
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
