version: '3.8'

services:
  app:
      image: ghcr.io/olivier-norture/toy-sale:dev
    network_mode: "host"
    depends_on:
      - db
    environment:
      - DB_HOST=127.0.0.1
      - DB_DATABASE=bourseauxjouets
      - DB_USER=user
      - DB_PASSWORD=password

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bourseauxjouets
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
